

services:
  flask_app:
    build:
      context: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://flaskadmin:8Byte$123@eight-byte-postgres.ceb8ecwkmdxo.us-east-1.rds.amazonaws.com:5432/flaskdb
        
   

  
