name: CI Pipeline

on:
  push:
    branches:
      - main


permissions:
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build, tag & push image to Docker Hub
        run: |
          docker build --pull -t ${{ secrets.DOCKER_USER }}/flask-app:latest flask-app/
          docker push ${{ secrets.DOCKER_USER }}/flask-app:latest

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh -o install.sh
          chmod +x install.sh
          sudo ./install.sh -b /usr/local/bin v0.74.0

      - name: Scan Docker image for vulnerabilities
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL --ignore-unfixed --pkg-types os ${{ secrets.DOCKER_USER }}/flask-app:latest
          docker run --rm ${{ secrets.DOCKER_USER }}/flask-app:latest sh -c "pip install --no-cache-dir pip-audit && pip-audit"
          
      - name: Scan terraform & helm files for security issues using Trivy
        run: |
          trivy fs --scanners misconfig --skip-dirs '**/.terraform' --exit-code 1 --severity HIGH,CRITICAL flask-CRUD-infra/terraform
          trivy fs --scanners misconfig --skip-dirs '**/.terraform' --exit-code 1 --severity HIGH,CRITICAL flask-CRUD-infra/helm
          
      - name: Download Trivy HTML template
        run: |
          mkdir -p contrib
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl -o contrib/html.tpl

      - name: Run Trivy with HTML Template
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          scanners: 'vuln,misconfig,secret'
          format: 'template'
          template: '@contrib/html.tpl'
          output: 'trivy-report.html'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Upload HTML Dashboard Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-html-dashboard
          path: trivy-report.html
          retention-days: 7