name: Continuous Integration

on:
    push:
        branches: [main]

jobs:
    test:
        name: Dockerize the application
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4
        
        - name: Login to docker
          uses: docker/login-action@v3
          with: 
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_TOKEN }}        

        - name: Build, tag & push image to docker hub
          run: |
            docker build -t ${{ secrets.DOCKER_USER }}/flask-img:latest flask-app/
            docker push ${{ secrets.DOCKER_USER }}/flask-img:latest
          